language: node_js
node_js:
    - 7
cache:
    directories:
        - node_modules
        - packages/create-react-app/node_modules
        - packages/react-scripts/node_modules
script:
    - npm test-ci
    - npm run build
